name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettify-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify JSON files
        run: |
          npm install -g json-format-cli
          find . -type f -name '*.json' -exec json-format -i {} -o {} \;
          git add .
          git diff --quiet --exit-code || git commit -m "Prettify JSON files"
