name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettify-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Use version 14 or higher to meet the requirements of actions/checkout@v4

      - name: Install json-format-cli
        run: npm install -g json-format-cli

      - name: Prettify JSON files
        run: |
          find . -type f -name '*.json' -exec json-format -i {} -o {} \;
          git add .
          git diff --quiet --exit-code || git commit -m "Prettify JSON files"

      - name: Debug Step
        run: |
          echo "Debugging information"
         # Run additional commands for debugging

      - name: Check json-format-cli version
        run: json-format --version
