name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

       - name: Install json-format-cli
        run: npm install -g json-format-cli

      - name: Prettify JSON files
        run: |
          find . -type f -name '*.json' -exec json-format -i {} -o {} \;
          git add .
          git diff --quiet --exit-code || git commit -m "Prettify JSON files"
